<?php

class FormaResponsive extends TablaFormulario
{
  public $modoBoton = "OFF";
  public $atributosFormulario = array("action"=>"/action_page.php");
  public $itemsTabla =  array(
                                  array(
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "LabelFname"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla25"
                                                                      ),
                                                    )
                                              ),
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "CajaTextoFnameResponsive"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla75"
                                                                      ),
                                                    )
                                              ),
                                        ),
                                  array(
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "LabelLname"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla25"
                                                                      ),
                                                    )
                                              ),
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "CajaTextoLnameResponsive"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla75"
                                                                      ),
                                                    )
                                              ),
                                        ),
                                  array(
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "LabelCountry"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla25"
                                                                      ),
                                                    )
                                              ),
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "SelectCountrySimple"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla75"
                                                                      ),
                                                    )
                                              ),
                                        ),
                                  array(
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "LabelSubject"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla25"
                                                                      ),
                                                    )
                                              ),
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "TextareaFormaResponsive"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla75"
                                                                      ),
                                                    )
                                              ),
                                        ),
                                  array(
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "Espacio"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla25"
                                                                      ),
                                                    )
                                              ),
                                        array(
                                              array(
                                                    "elemento"=>array(
                                                                      "SubmitForma"
                                                                     ),
                                                    "etiqueta"=>array(
                                                                      "DivColumnaTabla75"
                                                                      ),
                                                    )
                                              ),
                                        ),
                                );

}

?>
