<?php

class CargarClasesProyecto extends IAutoCargarClases
{
	public $directorios = array(
								/*"/var/www/html/php/proyecto/elementosPaginas/fieldset/",
								"/var/www/html/php/proyecto/elementosPaginas/textArea/",
								"/var/www/html/php/proyecto/elementosPaginas/select/",
								"/var/www/html/php/proyecto/elementosPaginas/checkbox/",
								"/var/www/html/php/proyecto/elementosPaginas/radio/",
								"/var/www/html/php/proyecto/elementosPaginas/span/",
								"/var/www/html/php/proyecto/elementosPaginas/header/",
								"/var/www/html/php/proyecto/elementosPaginas/section/",
								"/var/www/html/php/proyecto/elementosPaginas/nav/",
								"/var/www/html/php/proyecto/elementosPaginas/article/",
								"/var/www/html/php/proyecto/elementosPaginas/footer/",
								"/var/www/html/php/proyecto/elementosPaginas/tablas/",
								"/var/www/html/php/proyecto/elementosPaginas/botones/",
								"/var/www/html/php/proyecto/elementosPaginas/div/",
								"/var/www/html/php/proyecto/elementosPaginas/encabezados/",
PATHDIRECTORIOELEMENTOS."/tablas/",
								"/var/www/html/php/proyecto/elementosPaginas/imagenes/",
								"/var/www/html/php/proyecto/elementosPaginas/parrafos/",
								"/var/www/html/php/proyecto/elementosPaginas/listas/",
								"/var/www/html/php/proyecto/elementosPaginas/formularios/",
								"/var/www/html/php/proyecto/elementosPaginas/cajasTexto/",
								"/var/www/html/php/proyecto/elementosPaginas/textos/",
								"/var/www/html/php/proyecto/elementosPaginas/botonesSubmit/",
								"/var/www/html/php/proyecto/elementosPaginas/utilitarios/",
								"/var/www/html/php/proyecto/elementosPaginas/iframes/",*/
								PATHDIRECTORIOELEMENTOS."/imagenes/",
								PATHDIRECTORIOELEMENTOS."/tablas/",
								PATHDIRECTORIOELEMENTOS."/parrafoCompuesto/",
								PATHDIRECTORIOELEMENTOS."/titulo/",
								PATHDIRECTORIOELEMENTOS."/parrafos/",
								PATHDIRECTORIOELEMENTOS."/tituloParrafo/",
								PATHDIRECTORIOELEMENTOS."/utilitarios/",
								PATHDIRECTORIOELEMENTOS."/enlaces/",
								PATHDIRECTORIO."/elementosPaginas/",
								PATHDIRECTORIO."/vistas/",
								PATHDIRECTORIO."/paginas/",
								PATHDIRECTORIO."/config/",
							   );
}
?>
