<?php

class DivMenu extends EtiquetaDivHtml
{

	    public $elementos = array(
									"Espaciador",
									"EnlacePaginaPrincipal",
									"Espaciador",
									"EnlacePaginaSecundaria",
									"Espaciador",
									"EnlacePaginaTerciaria",
									"Espaciador",
									"EnlaceLista",
									"Espaciador",
									"EnlaceFormulario",
									"Espaciador",
									"EnlaceSaltoCapitulo",
									"Espaciador",
									"EnlaceMapaImagen",
									"Espaciador",
									"EnlaceElementosImagen",
									"Espaciador",
									"EnlaceTablas",
									"Espaciador",
									"EnlaceBloqueEnLinea",
									"Espaciador",
									"EnlaceClases",
									"Espaciador",
									"EnlaceOcultarTexto",
									"Espaciador",
									"EnlaceId",
									"Espaciador",
									"EnlaceIframes",
									"Espaciador",
									"EnlaceJavaScript",
									"Espaciador",
									"EnlaceLayOut",
									"Espaciador",
									"EnlaceResponsive",
                  "Espaciador",
									"EnlaceMediaQueries",
									"Espaciador",
									"EnlaceRWP",
									"Espaciador",
									"EnlaceW3CSS",
									"Espaciador",
									"EnlaceBootstrap",
									"Espaciador",
									"EnlaceCompuCode",
									"Espaciador",
									"EnlaceSemanticElements",
									"Espaciador",
									"EnlaceFormsHtml",
									"Espaciador",
									"EnlaceInputsHtml",
									"Espaciador",
									"EnlaceInputAttributesHtml",
									"Espaciador",
									"EnlaceFormAttributesHtml",
									"Espaciador",
									"EnlaceCanvasHtml",
									"Espaciador",
									"EnlaceSVGHtml",
									"Espaciador",
									"EnlaceMultimedia",
									"Espaciador",
									"EnlacePlugins",
									"Espaciador",
									"EnlaceYoutube",
									"Espaciador",
									"EnlaceGeolocation",
									"Espaciador",
									"EnlaceDragDropHtml",
									"Espaciador",
									"EnlaceWebStorage",
									"Espaciador",
									"EnlaceWebWorker",
									"Espaciador",
									"EnlaceSSE",
									"Espaciador",
																	);

    public function __construct()
    {
		parent::__construct();
    }


}

?>
